---
- name: config tsinghua apt
  shell: |
    cp /etc/apt/sources.list /etc/apt/sources.list.bak
    sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
    sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    curl -fsSL http://apt.yovole.tech/docker-ce/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] http://apt.yovole.tech/docker-ce $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

- name: remove old file /usr/share/keyrings/docker-archive-keyring.gpg
  file: path=/usr/share/keyrings/docker-archive-keyring.gpg  state=absent

- name: add docker's official GPG key
  shell: "curl -fsSL http://apt.yovole.tech/docker-ce/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

- name: set docker repo
  shell: >
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
    http://apt.yovole.tech/docker-ce $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

- name: apt update cache
  apt: update_cache=yes

- name: install depend pkgs
  apt: name={{ item }} state=latest
  loop:
    - curl
    - gnupg
    - lsb-release
    - ca-certificates
    - ipvsadm
    - iptables
    - traceroute
    - net-tools
    - initramfs-tools
    - ceph
    - gcc
    - make
    - pciutils
    - wget
    - screen
    - bind9-utils 
    - lvm2 
    - docker-ce
    - containerd.io 
    - nvidia-docker2 
    - nvidia-container-toolkit
    - chrony

- name: apt upgrade
  apt: upgrade=dist
