---
- name: Replace grub iommu
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=.*)'
    replace: 'GRUB_CMDLINE_LINUX="intel_iommu=on iommu=pt"'

- name: update grub2
  shell: update-grub2

- name: disable nouveau module
  shell: echo "blacklist nouveau \noptions nouveau modset=0" >> /etc/modprobe.d/blacklist.conf

- name: renew initramfs image
  shell: update-initramfs -u

- name: copy NVIDIA driver
  copy: src=NVIDIA-Linux-x86_64-470.94.run dest=/root mode=0644
